import { v4 as uuidv4 } from 'uuid';

export const Videos = [
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/qdIpKdFIJhU/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/qdIpKdFIJhU/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/3cbnNwxtUUA/hqdefault_live.jpg',
    imageSrc: 'https://i.ytimg.com/vi/3cbnNwxtUUA/hqdefault_live.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/2_144W4pIa0/hqdefault_live.jpg',
    imageSrc: 'https://i.ytimg.com/vi/2_144W4pIa0/hqdefault_live.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/Ixa5KWyhDBY/hqdefault_live.jpg',
    imageSrc: 'https://i.ytimg.com/vi/Ixa5KWyhDBY/hqdefault_live.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/CLexHGdzPYc/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/CLexHGdzPYc/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/lqwc7IOfgH8/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/lqwc7IOfgH8/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/k2qgadSvNyU/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/k2qgadSvNyU/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/dw7QFZuqLxQ/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/dw7QFZuqLxQ/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/lVVLZ5qz1HI/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/lVVLZ5qz1HI/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/sF_dYGhA9Bk/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/sF_dYGhA9Bk/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/OyZDmPkKcRw/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/OyZDmPkKcRw/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/KSuCUigi8dQ/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/KSuCUigi8dQ/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/5osRseGB7zI/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/5osRseGB7zI/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/hzZRRf4rJDM/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/hzZRRf4rJDM/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/nzG5r70_iBs/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/nzG5r70_iBs/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/XbssmfYVqI8/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/XbssmfYVqI8/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/ah6hYo3tkbk/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/ah6hYo3tkbk/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/gp62VvoYid8/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/gp62VvoYid8/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/pfn-GDnRjm4/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/pfn-GDnRjm4/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/XeDbyVODQ5M/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/XeDbyVODQ5M/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/gW8O0MkdzTg/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/gW8O0MkdzTg/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/0StZBC4Hhq0/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/0StZBC4Hhq0/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/Y5K9HBiJpuk/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/Y5K9HBiJpuk/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/dMVIM21b7lw/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/dMVIM21b7lw/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/6jyMQwzbmOs/hqdefault_live.jpg',
    imageSrc: 'https://i.ytimg.com/vi/6jyMQwzbmOs/hqdefault_live.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/feigIqugUsA/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/feigIqugUsA/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/iFOmNjI_2AA/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/iFOmNjI_2AA/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/bhghAm_biGU/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/bhghAm_biGU/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/nwXuPRPdZbs/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/nwXuPRPdZbs/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/VKCdjL-70dc/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/VKCdjL-70dc/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/EMZitR0Ubcw/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/EMZitR0Ubcw/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/uxmguZS_KZo/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/uxmguZS_KZo/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/6ZKDdzqN6B4/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/6ZKDdzqN6B4/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/qqrpMRDuPfc/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/qqrpMRDuPfc/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/gGlyiFsqAO0/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/gGlyiFsqAO0/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/COaWEUMSR0U/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/COaWEUMSR0U/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/Wp5hyfQ0P80/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/Wp5hyfQ0P80/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/fvYIlNaPNiE/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/fvYIlNaPNiE/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/TyUQnDG0VxI/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/TyUQnDG0VxI/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/9fwD77TW16c/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/9fwD77TW16c/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/2w8KUgIkAu8/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/2w8KUgIkAu8/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/WDlTm3XiGn8/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/WDlTm3XiGn8/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/J2-sMGzMKEU/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/J2-sMGzMKEU/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/70_2DcsIncY/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/70_2DcsIncY/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/i9UDD6zyCGs/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/i9UDD6zyCGs/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/l95RuKCvj8k/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/l95RuKCvj8k/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/e4BLgyxG1lM/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/e4BLgyxG1lM/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/sVTy_wmn5SU/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/sVTy_wmn5SU/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/YFavIKYwZOM/hqdefault_live.jpg',
    imageSrc: 'https://i.ytimg.com/vi/YFavIKYwZOM/hqdefault_live.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
  {
    price: 100,
    name: 'video',
    url: 'https://i.ytimg.com/vi/5e4INH1yr9c/hqdefault.jpg',
    imageSrc: 'https://i.ytimg.com/vi/5e4INH1yr9c/hqdefault.jpg',
    width: 480,
    height: 360,
    isActive: true,
    id: uuidv4(),
  },
];
